name: TOS
main: io.github.stefnotch.tos.TOS
version: 1.8-R0.1-SNAPSHOT
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   whisper:
      description: It whispers a message to a player.
      usage: /whisper <player> <message>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>